name: test reusable workflow

on:
  workflow_call:
    inputs:
      mytag:
        required: true
        type: string
    secrets:
      DOCKER_USER_NAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v main.go

    - name: go build
      run: go build -o main -v main.go

    - name: login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: image build and push
      run: |
        # Build a docker container and push it to ECR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        image_tag=${{ inputs.mytag }}.$git_hash
        docker build -t chendazhen/gitops-webapp-demo:$image_tag .
        echo "Pushing image to dockerhub..."
        docker push chendazhen/gitops-webapp-demo:$image_tag
        echo "::set-output name=image::chendazhen/gitops-webapp-demo:$image_tag"

    - name: update image version
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        sed -r -i "s/(^.*newTag:).*/\1 $git_hash/" ./deployment/dev/kustomization.yaml
        sed -r -i "s/(^.*newTag:).*/\1 $git_hash/" ./deployment/prod/kustomization.yaml

    - name: commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.TOKEN }}
        commit_message: Version update
