name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: go test -v main.go

    - name: go build
      run: go build -o main -v main.go

    - name: login dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: image build and push
      run: |
        # Build a docker container and push it to ECR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t chendazhen/gitops-webapp-demo:$git_hash .
        echo "Pushing image to dockerhub..."
        docker push chendazhen/gitops-webapp-demo:$git_hash
        echo "::set-output name=image::chendazhen/gitops-webapp-demo:$git_hash"
        
    - name: update image version
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        sed -r -i 's/(^.*image: ).*/\1 chendazhen\/gitops-webapp-demo:$git_hash/' ./deployment/dev/deployment.yaml
        sed -r -i 's/(^.*image: ).*/\1 chendazhen\/gitops-webapp-demo:$git_hash/' ./deployment/prod/deployment.yaml

    - name: commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.TOKEN }}
        commit_messages: Version update

