name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: go test -v main.go

    - name: go build
      run: go build -o main -v main.go

    - name: image build and push
      run: |
        # Build a docker container and push it to ECR
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t chendazhen/gitops-webapp-demo:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to ECR..."
        docker push chendazhen/gitops-webapp-demo:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=image::chendazhen/gitops-webapp-demo:${GITHUB_REF##*/}-$git_hash"
        
    - name: update image version
