name: prod

on:
  push:
    branches: [ master ]
    paths:
      - deployment/prod/**
  pull_request:
    branches: [ master ]
    paths:
      - deployment/prod/**

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mytag: dchen1
    secrets:
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
