name: prod

on:
  push:
    branches: [ master ]
    paths:
      - deployment/prod/**
  pull_request:
    branches: [ master ]
    paths:
      - deployment/prod/**

jobs:
  build:
    uses: .workflows/build.yaml
    with:
      mytag: dchen1
